"""empty message

Revision ID: 011b1fa661c1
Revises: e33ddeddba23
Create Date: 2021-09-15 18:12:42.967155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '011b1fa661c1'
down_revision = 'e33ddeddba23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('complete', sa.Integer(), nullable=False))
    op.drop_column('projects', 'repository_link')
    op.add_column('sprints', sa.Column('complete', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprints', 'complete')
    op.add_column('projects', sa.Column('repository_link', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('projects', 'complete')
    # ### end Alembic commands ###
