"""empty message

Revision ID: 0500723ab8c4
Revises: c3fb2b6ff56f
Create Date: 2021-09-14 09:24:07.619829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0500723ab8c4'
down_revision = 'c3fb2b6ff56f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprints_and_users',
    sa.Column('users_id', sa.String(length=128), nullable=False),
    sa.Column('sprints_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['sprints_id'], ['sprints.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'sprints_id')
    )
    op.add_column('sprints', sa.Column('project_id', sa.String(length=128), nullable=True))
    op.drop_constraint('sprints_ibfk_1', 'sprints', type_='foreignkey')
    op.create_foreign_key(None, 'sprints', 'projects', ['project_id'], ['id'])
    op.drop_column('sprints', 'project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('project', mysql.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'sprints', type_='foreignkey')
    op.create_foreign_key('sprints_ibfk_1', 'sprints', 'projects', ['project'], ['id'])
    op.drop_column('sprints', 'project_id')
    op.drop_table('sprints_and_users')
    # ### end Alembic commands ###
