"""empty message

Revision ID: 06363366f29e
Revises: 423b4647d056
Create Date: 2021-09-10 22:00:38.063623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06363366f29e'
down_revision = '423b4647d056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
