"""empty message

Revision ID: 423b4647d056
Revises: 
Create Date: 2021-09-09 15:38:47.880353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423b4647d056'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('msg', sa.String(length=256), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
