"""empty message

Revision ID: 68802e862f10
Revises: 47dba9c92006
Create Date: 2021-07-28 20:56:03.765450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68802e862f10'
down_revision = '47dba9c92006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('users_id', sa.String(length=128), nullable=False))
    op.add_column('association', sa.Column('projects_id', sa.String(length=128), nullable=False))
    op.drop_constraint('association_ibfk_2', 'association', type_='foreignkey')
    op.drop_constraint('association_ibfk_1', 'association', type_='foreignkey')
    op.create_foreign_key(None, 'association', 'projects', ['projects_id'], ['id'])
    op.create_foreign_key(None, 'association', 'users', ['users_id'], ['id'])
    op.drop_column('association', 'user_id')
    op.drop_column('association', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('project_id', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('association', sa.Column('user_id', mysql.VARCHAR(length=128), nullable=False))
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.create_foreign_key('association_ibfk_1', 'association', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('association_ibfk_2', 'association', 'users', ['user_id'], ['id'])
    op.drop_column('association', 'projects_id')
    op.drop_column('association', 'users_id')
    # ### end Alembic commands ###
