"""empty message

Revision ID: 6d31dc99a2c5
Revises: 
Create Date: 2021-07-08 09:10:47.088164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d31dc99a2c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_templates',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('project_template_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('repository', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['project_template_id'], ['project_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sprint_templates',
    sa.Column('project_template_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['project_template_id'], ['project_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sprints',
    sa.Column('sprint_template_id', sa.String(length=128), nullable=True),
    sa.Column('project_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sprint_template_id'], ['sprint_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_templates',
    sa.Column('sprint_template_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['sprint_template_id'], ['sprint_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_templates')
    op.drop_table('sprints')
    op.drop_table('sprint_templates')
    op.drop_table('projects')
    op.drop_table('project_templates')
    # ### end Alembic commands ###
