"""empty message

Revision ID: 7ebf40c5c0e8
Revises: 
Create Date: 2021-09-14 12:08:33.248003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ebf40c5c0e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('user_handle', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('user_link', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('sprint_name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('sprint_link', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('project_name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('project_link', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('message', mysql.VARCHAR(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
