"""empty message

Revision ID: 85ae6974e429
Revises: 23d8c926c1bd
Create Date: 2021-07-19 05:48:23.589197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85ae6974e429'
down_revision = '23d8c926c1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_templates', 'name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('project_templates', 'link',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('project_templates', 'author',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('project_templates', 'tech_dependencies',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('project_templates', 'role_types',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('project_templates', 'description',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('project_templates', 'goals',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('project_templates', 'quiz',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('sprint_templates', 'number',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('sprint_templates', 'tech_dependencies',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('sprint_templates', 'role_types',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('sprint_templates', 'description',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('sprint_templates', 'goals',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('sprint_templates', 'quiz',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('sprints', 'roles',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('task_templates', 'number',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('task_templates', 'tech_dependencies',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('task_templates', 'role_types',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('task_templates', 'description',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('task_templates', 'goals',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('task_templates', 'tests',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('tasks', 'role',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'role',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('task_templates', 'tests',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('task_templates', 'goals',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('task_templates', 'description',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('task_templates', 'role_types',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('task_templates', 'tech_dependencies',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('task_templates', 'number',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('sprints', 'roles',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('sprint_templates', 'quiz',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('sprint_templates', 'goals',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('sprint_templates', 'description',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('sprint_templates', 'role_types',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('sprint_templates', 'tech_dependencies',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('sprint_templates', 'number',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('project_templates', 'quiz',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('project_templates', 'goals',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('project_templates', 'description',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('project_templates', 'role_types',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('project_templates', 'tech_dependencies',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('project_templates', 'author',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('project_templates', 'link',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('project_templates', 'name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
