"""empty message

Revision ID: 8d9a215e50e2
Revises: fe436d206f55
Create Date: 2021-07-08 10:09:06.757140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d9a215e50e2'
down_revision = 'fe436d206f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learn_resources', 'articles',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('learn_resources', 'videos',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('learn_resources', 'external_links',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.add_column('project_templates', sa.Column('link', sa.String(length=128), nullable=False))
    op.add_column('project_templates', sa.Column('author', sa.String(length=128), nullable=False))
    op.add_column('project_templates', sa.Column('tech_dependencies', sa.String(length=128), nullable=False))
    op.add_column('project_templates', sa.Column('role_types', sa.String(length=128), nullable=False))
    op.add_column('project_templates', sa.Column('description', sa.String(length=256), nullable=False))
    op.add_column('project_templates', sa.Column('goals', sa.String(length=128), nullable=False))
    op.add_column('project_templates', sa.Column('quiz', sa.String(length=128), nullable=False))
    op.add_column('projects', sa.Column('repository_link', sa.String(length=128), nullable=False))
    op.add_column('projects', sa.Column('progress', sa.String(length=128), nullable=True))
    op.add_column('projects', sa.Column('quiz_status', sa.String(length=128), nullable=True))
    op.add_column('projects', sa.Column('roles', sa.String(length=128), nullable=False))
    op.drop_column('projects', 'repository')
    op.add_column('sprint_templates', sa.Column('number', sa.Integer(), nullable=False))
    op.add_column('sprint_templates', sa.Column('tech_dependencies', sa.String(length=128), nullable=False))
    op.add_column('sprint_templates', sa.Column('role_types', sa.String(length=128), nullable=False))
    op.add_column('sprint_templates', sa.Column('description', sa.String(length=256), nullable=False))
    op.add_column('sprint_templates', sa.Column('goals', sa.String(length=128), nullable=False))
    op.add_column('sprint_templates', sa.Column('quiz', sa.String(length=128), nullable=False))
    op.add_column('sprints', sa.Column('progress', sa.String(length=128), nullable=True))
    op.add_column('sprints', sa.Column('quiz_status', sa.String(length=128), nullable=True))
    op.add_column('sprints', sa.Column('roles', sa.String(length=128), nullable=False))
    op.add_column('task_templates', sa.Column('number', sa.Integer(), nullable=False))
    op.add_column('task_templates', sa.Column('tech_dependencies', sa.String(length=128), nullable=False))
    op.add_column('task_templates', sa.Column('role_types', sa.String(length=128), nullable=False))
    op.add_column('task_templates', sa.Column('description', sa.String(length=256), nullable=False))
    op.add_column('task_templates', sa.Column('goals', sa.String(length=128), nullable=False))
    op.add_column('task_templates', sa.Column('tests', sa.String(length=128), nullable=False))
    op.add_column('tasks', sa.Column('status', sa.String(length=128), nullable=False))
    op.add_column('tasks', sa.Column('role', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'role')
    op.drop_column('tasks', 'status')
    op.drop_column('task_templates', 'tests')
    op.drop_column('task_templates', 'goals')
    op.drop_column('task_templates', 'description')
    op.drop_column('task_templates', 'role_types')
    op.drop_column('task_templates', 'tech_dependencies')
    op.drop_column('task_templates', 'number')
    op.drop_column('sprints', 'roles')
    op.drop_column('sprints', 'quiz_status')
    op.drop_column('sprints', 'progress')
    op.drop_column('sprint_templates', 'quiz')
    op.drop_column('sprint_templates', 'goals')
    op.drop_column('sprint_templates', 'description')
    op.drop_column('sprint_templates', 'role_types')
    op.drop_column('sprint_templates', 'tech_dependencies')
    op.drop_column('sprint_templates', 'number')
    op.add_column('projects', sa.Column('repository', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('projects', 'roles')
    op.drop_column('projects', 'quiz_status')
    op.drop_column('projects', 'progress')
    op.drop_column('projects', 'repository_link')
    op.drop_column('project_templates', 'quiz')
    op.drop_column('project_templates', 'goals')
    op.drop_column('project_templates', 'description')
    op.drop_column('project_templates', 'role_types')
    op.drop_column('project_templates', 'tech_dependencies')
    op.drop_column('project_templates', 'author')
    op.drop_column('project_templates', 'link')
    op.alter_column('learn_resources', 'external_links',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('learn_resources', 'videos',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('learn_resources', 'articles',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
