"""empty message

Revision ID: 8ea66ef31852
Revises: 85ae6974e429
Create Date: 2021-07-28 19:00:19.613977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ea66ef31852'
down_revision = '85ae6974e429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'projects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('projects', mysql.VARCHAR(length=256), nullable=True))
    op.drop_table('teams')
    # ### end Alembic commands ###
