"""empty message

Revision ID: a305055b4f31
Revises: b7c903008cef
Create Date: 2021-07-07 08:31:47.069680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a305055b4f31'
down_revision = 'b7c903008cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', sa.String(length=128), nullable=False))
    op.drop_column('projects', 'descrition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('descrition', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###
