"""empty message

Revision ID: ae7eb24d9037
Revises: d61403e69a63
Create Date: 2021-07-28 20:42:48.125397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7eb24d9037'
down_revision = 'd61403e69a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'new')
    # ### end Alembic commands ###
