"""empty message

Revision ID: b7c903008cef
Revises: 
Create Date: 2021-07-07 08:14:37.346216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c903008cef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('repository', sa.String(length=128), nullable=False),
    sa.Column('descrition', sa.String(length=128), nullable=False),
    sa.Column('preview_images', sa.String(length=128), nullable=False),
    sa.Column('videos', sa.String(length=128), nullable=False),
    sa.Column('resources', sa.String(length=128), nullable=False),
    sa.Column('quizzes', sa.String(length=128), nullable=False),
    sa.Column('goals', sa.String(length=128), nullable=False),
    sa.Column('dependencies', sa.String(length=128), nullable=False),
    sa.Column('progress', sa.String(length=128), nullable=False),
    sa.Column('sprints', sa.String(length=128), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
