"""empty message

Revision ID: b878ea43f094
Revises: 
Create Date: 2021-09-12 13:26:57.887815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b878ea43f094'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('repository_name', sa.String(length=128), nullable=True))
    op.add_column('projects', sa.Column('owner_handle', sa.String(length=128), nullable=True))
    op.drop_column('projects', 'progress')
    op.drop_column('projects', 'roles')
    op.drop_column('projects', 'project_template_id')
    op.drop_column('projects', 'quiz_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('quiz_status', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('projects', sa.Column('project_template_id', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('projects', sa.Column('roles', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('projects', sa.Column('progress', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('projects', 'owner_handle')
    op.drop_column('projects', 'repository_name')
    # ### end Alembic commands ###
