"""empty message

Revision ID: c3fb2b6ff56f
Revises: b878ea43f094
Create Date: 2021-09-14 09:03:24.589789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3fb2b6ff56f'
down_revision = 'b878ea43f094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprints',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('progress', sa.String(length=128), nullable=False),
    sa.Column('project', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sprints')
    # ### end Alembic commands ###
