"""empty message

Revision ID: cbe0a672480b
Revises: d2c16f13b1b0
Create Date: 2021-07-28 19:31:14.948015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbe0a672480b'
down_revision = 'd2c16f13b1b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    op.drop_table('roles')
    op.add_column('users', sa.Column('projects', sa.String(length=256), nullable=True))
    op.drop_column('users', 'about_me')
    op.drop_column('users', 'culture')
    op.drop_column('users', 'title')
    op.drop_column('users', 'interests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('interests', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('users', sa.Column('title', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('users', sa.Column('culture', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('users', sa.Column('about_me', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('users', 'projects')
    op.create_table('roles',
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('teams',
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
