"""empty message

Revision ID: d2c16f13b1b0
Revises: 8ea66ef31852
Create Date: 2021-07-28 19:11:47.766688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c16f13b1b0'
down_revision = '8ea66ef31852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('interests', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('about_me', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('culture', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('title', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'title')
    op.drop_column('users', 'culture')
    op.drop_column('users', 'about_me')
    op.drop_column('users', 'interests')
    op.drop_table('roles')
    # ### end Alembic commands ###
