"""empty message

Revision ID: d312f79dec5b
Revises: 909b6c8657f9
Create Date: 2021-09-15 21:48:26.453559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd312f79dec5b'
down_revision = '909b6c8657f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('test', sa.Integer(), autoincrement=True, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprints', 'test')
    # ### end Alembic commands ###
