"""empty message

Revision ID: d61403e69a63
Revises: cbe0a672480b
Create Date: 2021-07-28 19:52:52.748503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd61403e69a63'
down_revision = 'cbe0a672480b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.add_column('users', sa.Column('interests', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('about_me', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('culture', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('title', sa.String(length=256), nullable=True))
    op.drop_column('users', 'projects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('projects', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('users', 'title')
    op.drop_column('users', 'culture')
    op.drop_column('users', 'about_me')
    op.drop_column('users', 'interests')
    op.drop_table('association')
    # ### end Alembic commands ###
