"""empty message

Revision ID: dfb942ac0537
Revises: 68802e862f10
Create Date: 2021-08-31 20:58:56.762004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb942ac0537'
down_revision = '68802e862f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles_of_interest', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'roles_of_interest')
    # ### end Alembic commands ###
