"""empty message

Revision ID: fcbdb9275014
Revises: 39a4f93540f5
Create Date: 2021-09-14 12:49:35.898045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcbdb9275014'
down_revision = '39a4f93540f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('project_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'project_name')
    # ### end Alembic commands ###
