"""empty message

Revision ID: fe436d206f55
Revises: 5a412e98d4c9
Create Date: 2021-07-08 09:42:30.548612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe436d206f55'
down_revision = '5a412e98d4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_template_id', sa.String(length=128), nullable=True),
    sa.Column('sprint_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ),
    sa.ForeignKeyConstraint(['task_template_id'], ['task_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
